name: 'IBM Cloud CLI'
description: 'Install and configure IBM Cloud CLI to talk to IBM Cloud'
inputs:
  APIKEY: # APIKEY
    description: 'Your API key to access IBM Cloud'
    required: true
  CLOUD_REGION: # REGION
    description: 'The region to access IBM Cloud'
    required: true
    default: 'us-south'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.APIKEY }}
    - ${{ inputs.CLOUD_REGION }}
